# Generated by Django 2.2.2 on 2019-08-11 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TeachFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
                ('img', models.ImageField(blank=True, upload_to='media/upload/file/')),
                ('size', models.IntegerField(blank=True)),
                ('typefile', models.CharField(blank=True, max_length=9)),
                ('linkfile', models.URLField(blank=True)),
            ],
        ),
    ]
