# Generated by Django 2.2.2 on 2019-08-11 22:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teach', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='teachfile',
            options={'verbose_name': 'Файл', 'verbose_name_plural': 'Файлы'},
        ),
    ]
