# Generated by Django 2.2.2 on 2019-08-12 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teach', '0002_auto_20190811_2213'),
    ]

    operations = [
        migrations.AddField(
            model_name='teachfile',
            name='file',
            field=models.FileField(blank=True, upload_to='media/upload/files/'),
        ),
    ]
