# Generated by Django 2.2.2 on 2019-08-11 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newspost',
            name='img',
            field=models.ImageField(blank=True, upload_to='media/upload'),
        ),
    ]
