# Generated by Django 2.2.2 on 2019-08-11 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_auto_20190811_1838'),
    ]

    operations = [
        migrations.AddField(
            model_name='newspost',
            name='avilable',
            field=models.BooleanField(default=True),
        ),
    ]
